export const POOL_REST_CONNECTION_URL = 'POOL_REST_CONNECTION_URL';
export const POOL_REST_TIMER_UPDATE = 'POOL_REST_TIMER_UPDATE';
export const POOL_REST_CONNECTION_URL_VALUE = 'http://94.19.151.45/api/';
export const POOL_REST_TIMER_UPDATE_VALUE = 20000;
